@startuml
MMSorter -> Camera: getFrame()
Camera --> MMSorter: Picture
MMSorter -> MMPicture: findMM()

MMPicture -> BoundsDetector: locateObjects()
BoundsDetector -> MMPicture: List<Object>

loop foreach Object
    MMPicture -> ColorDetector: detectColor()
    ColorDetector -> MMPicture : Color
    alt Color is null
       MMPicture -> HardwareController: feed()
    else
        MMPicture -> HardwareController: openGate(color)
    end

end

@enduml